### ISSUE TITLE
Changed github nickname. Some packages does not get updated

### ISSUE THREAD

**Issue by FreeSlave** [dlang/dub-registry#181]
I changed my github nickname and updated Repository Owner for each my dub package on http://code.dlang.org/
Then I updated some links in my repos, pushed changes and created new tags (it's 14 hours ago already).
Strangely some packages got updated, while other did not.

E.g. http://code.dlang.org/packages/findexecutable got new version on code.dlang, but http://code.dlang.org/packages/isfreedesktop did not, even after triggering manual update. Can it be somehow connected to the nickname change on github?

**Comment by FreeSlave** [comment]
Seems like issue was resolved by itself.

**Comment by s-ludwig** [comment]
Unfortunately I was too slow to investigate this while it was still happening (or not happening). Would have been interesting to see what held it back.
